#!/usr/bin/env sh

launch="spotifyd"
kill="killall spotifyd"

case "$1" in
    "-s")
        [ "$(pgrep spotifyd | wc -l)" -gt "0" ] || "${launch}"
        ;;
    "-r")
        "${kill}"
        "${launch}"
        ;;
    "-k")
        "${kill}"
        ;;
    *)
        "${launch}"
        ;;
esac
