#!/usr/bin/env sh

dir="/tmp/xobpipes"

if [ "${1}" = "-r" ]; then
	rm -r "${dir}"
	pkill -f "tail -f ${dir}/bkl"
	pkill -f "tail -f ${dir}/kbd"
	pkill -f "tail -f ${dir}/vol"
	killall xob
fi

mkdir "${dir}"
mkfifo "${dir}/bkl"
tail -f "${dir}/bkl" | xob &
mkfifo "${dir}/kbd"
tail -f "${dir}/kbd" | xob &
mkfifo "${dir}/vol"
tail -f "${dir}/vol" | xob &
