#!/usr/bin/env bash

declare -A arr
arr+=(
[alacritty]="${HOME}/.config/alacritty/alacritty.yml"
[bspwm]="${HOME}/.config/bspwm/bspwmrc"
[dunst]="${HOME}/.config/dunst/dunstrc"
[firefox]="${HOME}/.config/firefox/userChrome.css"
[neovim]="${HOME}/.config/nvim/init.vim"
[picom]="${HOME}/.config/picom/picom.conf"
[polybar]="${HOME}/.config/polybar/config.ini"
[spotifyd]="${HOME}/.config/spotifyd/spotifyd.conf"
[sxkhd]="${HOME}/.config/sxhkd/sxhkdrc"
[xob]="${HOME}/.config/xob/styles.cfg"
[zsh]="${HOME}/.zshrc/"
)
choice="$(printf "%s\n" "${!arr[@]}" | dmenu -i -p "config menu:")"
[ ${?} = 0 ] && ${TERMINAL} -e ${EDITOR} ${arr[$choice]}
