#!/usr/bin/env sh

killall sxhkd; sxhkd &
killall dunst; dunst &
xsetroot -cursor_name left_ptr
${SCRIPTS}/set/wallpaper
${SCRIPTS}/launch/xob
${SCRIPTS}/launch/polybar -r
${SCRIPTS}/launch/picom -r

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           19
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc rule -a Zathura state=tiled
