#!/usr/bin/env sh

case $1 in
	--increase|-i)
		shift
		killall huadm
		hueadm light 1 +$1%
		hueadm light 2 +$1%
		break
		;;
	--decrease|-d)
		shift
		killall hueadm
		hueadm light 1 -$1%
		hueadm light 2 -$1%
		break
		;;
	--on|-n)
		shift
		hueadm light 1 on
		hueadm light 2 on
		break
		;;
	--off|-f)
		shift
		hueadm light 1 off
		hueadm light 2 off
		break
		;;
	--help|-h)
		echo "Set brightness of philips hue lights"
		echo ""
		echo "USAGE:"
		echo "	${0##*/} ACTION [ARG]"
		echo ""
		echo "ACTIONS:"
		echo "	-i, --increase <NUMBER>   Increase brightness"
		echo "	-d, --decrease <NUMBER>   Decrease brightness"
		echo "	-n, --on                  Turn lights on"
		echo "	-f, --off                 Turn lights off"
		exit 0
		;;
	*)
		echo "Unknown option '$1' (Try --help)"
		exit 1
		;;
esac
