#!/bin/sh

if [ "$1" = "-d" ]; then
	light -s sysfs/leds/smc::kbd_backlight -U "$2"
	light -s sysfs/leds/smc::kbd_backlight -G > /tmp/xobpipes/bkl
elif [ "$1" = "-i" ]; then
	light -s sysfs/leds/smc::kbd_backlight -A "$2"
	light -s sysfs/leds/smc::kbd_backlight -G > /tmp/xobpipes/bkl
else
	exit 1;
fi
