#!/bin/sh

if [ "$1" = "-i" ]; then
	pamixer --increase "$2"
	pamixer --get-volume > /tmp/xobpipes/vol
elif [ "$1" = "-d" ]; then
	pamixer --decrease "$2"
	pamixer --get-volume > /tmp/xobpipes/vol
elif [ "$1" = "-t" ]; then
	pamixer --toggle-mute
else
	exit 1
fi
